#!/home/ben/software/install/bin/perl
use warnings;
use strict;
use FindBin '$Bin';
use Path::Tiny;
use Date::Calc qw/Delta_YMDHMS Add_Delta_YMDHMS/;
my $file = path ("timesheet.txt");
my @lines = $file->lines_utf8 ();
my (@e, @s, @d);
my @f = (2000,1,1,0,0,0);
my @t = @f;
for (@lines) {
    if (/^#/) {
	next;
    }
    if (/[0-9]/) {
	if (@s) {
	    @e = get_times ($_);
	    @d = Delta_YMDHMS (@s, @e);
	    @t = Add_Delta_YMDHMS (@t, @d);
	    @e = ();
	    @s = ();
	}
	else {
	    @s = get_times ($_);
	}
    }
    else {
	if (!/\s+$/) {
	    die "Bad line $_";
	}
    }
}
@t = Delta_YMDHMS (@f, @t);
print "@t\n";
exit;
sub get_times
{
    my ($line) = @_;
    chomp $line;
    my @t = split /[^0-9]+/, $line;
    if (@t != 6) {
	die "Bad line $line";
    }
    return @t;
}


